# Generated by Django 4.2.16 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_queries',
            field=models.JSONField(help_text='The discovered queries for indirect host counting', null=True),
        ),
    ]
